# Generated by Django 5.2 on 2025-05-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(choices=[('technical', 'Technical'), ('financial', 'Financial'), ('general', 'General')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
