# Generated by Django 5.2 on 2025-04-25 01:50

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BootCamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(default='35.69967769328554,51.31804375220537', srid=4326)),
                ('students', models.ManyToManyField(related_name='Students_of_a_bootcamp', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(related_name='Teachers_of_a_bootcamp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
