# Generated by Django 5.2 on 2025-04-28 17:05

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bootcamps',
            options={'verbose_name': 'Bootcamp', 'verbose_name_plural': 'Bootcamps'},
        ),
        migrations.AlterField(
            model_name='bootcamps',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(35.69967769328554, 51.31804375220537), srid=4326),
        ),
    ]
