# Generated by Django 5.2 on 2025-05-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0002_alter_bootcamps_options_alter_bootcamps_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamps',
            name='enrollment_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bootcamps',
            name='price',
            field=models.BigIntegerField(default=100000000),
            preserve_default=False,
        ),
    ]
