# Generated by Django 5.2 on 2025-05-28 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0003_bootcamps_enrollment_status_bootcamps_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BootcampRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bootcamp.bootcamps')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_that_asked_for_enrollment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
