# Generated by Django 5.2 on 2025-04-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_headmaster_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicians',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='technicians',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='HeadMaster',
        ),
        migrations.DeleteModel(
            name='Technicians',
        ),
    ]
