# Generated by Django 5.2 on 2025-04-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_remove_technicians_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_add_headmaster', 'Can add headmaster'), ('can_list_headmasters', 'Can list headmasters'), ('can_delete_headmaster', 'Can delete headmaster'), ('can_retrieve_headmaster', 'Can retrieve headmaster'), ('can_add_technician', 'Can add technician'), ('can_list_technicians', 'Can list technicians'), ('can_delete_technician', 'Can delete technician'), ('can_retrieve_technician', 'Can retrieve technician')],
            },
        ),
    ]
