# Generated by Django 5.2 on 2025-05-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_transaction_to_transaction_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='wallet',
            new_name='user',
        ),
    ]
